[tool.isort]
line_length = 120
profile = "black"

[tool.black]
line_length = 120

[tool.pyright]
typeCheckingMode = "basic"

reportIncompatibleMethodOverride = "information"
reportPrivateImportUsage = "information"
reportOptionalSubscript = "none"

pythonVersion = "3.10"
pythonPlatform = "Linux"