[tool.isort]
line_length = 120
profile = "black"

[tool.black]
line_length = 120
target-version = ['py38', 'py39', 'py310']

[tool.pyright]
typeCheckingMode = "basic"

reportIncompatibleMethodOverride = "information"
reportPrivateImportUsage = "information"
reportOptionalSubscript = "none"

pythonVersion = "3.8"
pythonPlatform = "Linux"
