[tool.isort]
line_length = 120

[tool.black]
line_length = 120
target-version = ['py38']

[tool.pyright]
typeCheckingMode = "basic"

reportIncompatibleMethodOverride = "information"
reportPrivateImportUsage = "information"
reportOptionalSubscript = "none"

pythonVersion = "3.8"
pythonPlatform = "Linux"
# configurations -> https://github.com/microsoft/pyright/blob/main/docs/configuration.md
